//! Cumulative reductions (`cumsum` / `cumprod`).
//!
//! Both ops scan along a single `axis`. `reverse=true` flips the scan
//! direction; `inclusive=true` includes the element at the index in the
//! running aggregate (matching NumPy's default), `false` produces an
//! exclusive prefix scan.
//!
//! Default + `*_on` variants are generated by the
//! [`op_with_stream!`](crate::op_with_stream) macro.

use crate::{Array, Result};

op_with_stream! {
    /// Cumulative sum along `axis`. With `reverse=false, inclusive=true`,
    /// the result at index `i` is `sum(a[..=i])` (NumPy default). Setting
    /// `reverse=true` reverses the scan direction; `inclusive=false`
    /// produces an exclusive prefix scan.
    pub fn cumsum(a: &Array, axis: i32, reverse: bool, inclusive: bool) -> Result<Array>
        => mlx_sys::array::ffi::cumsum(a.as_inner(), axis, reverse, inclusive);
}

op_with_stream! {
    /// Cumulative product along `axis`. See [`cumsum`] for `reverse` and
    /// `inclusive` semantics.
    pub fn cumprod(a: &Array, axis: i32, reverse: bool, inclusive: bool) -> Result<Array>
        => mlx_sys::array::ffi::cumprod(a.as_inner(), axis, reverse, inclusive);
}
