# Engineering inventory policy for the Apple Silicon Release product.
# "accepted" selects a satisfiable license branch for deterministic notice
# generation; it is not a legal approval to publish IronMLX.
accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "Unlicense",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "Unicode-3.0",
    "MPL-2.0",
    "LGPL-2.1-or-later",
]
targets = ["aarch64-apple-darwin"]
ignore-dev-dependencies = true
ignore-build-dependencies = false
private = { ignore = true }
workarounds = ["ring", "rustls"]
