use ironmlx_audio::{features, AudioError, PcmBuffer, PcmFormat, Result, SessionControl};

struct Active;
impl SessionControl for Active {
    fn check(&self) -> Result<()> {
        Ok(())
    }
}
fn pcm(samples: Vec<f32>, sample_rate: u32) -> PcmBuffer {
    PcmBuffer {
        format: PcmFormat {
            sample_rate,
            channels: 1,
        },
        samples,
    }
}

#[test]
fn bounded_features_padding_and_cancellation() {
    let audio = pcm(vec![0.; 16160], 16000);
    let semantic = features::semantic_features(&audio, &Active).unwrap();
    assert_eq!(semantic.features.frames(), 50);
    assert_eq!(semantic.features.width(), 160);
    assert_eq!(semantic.attention_mask.last(), Some(&0));
    assert_eq!(&semantic.features.values()[50 * 160 - 80..], &[1.; 80]);
    assert!(semantic.features.values().iter().all(|x| x.is_finite()));
    assert!(features::reference_mel(&audio, &Active).is_err());
    assert!(features::speaker_fbank(&pcm(vec![0.; 15999], 16000), &Active).is_err());
    struct Cancelled;
    impl SessionControl for Cancelled {
        fn check(&self) -> Result<()> {
            Err(AudioError::Cancelled)
        }
    }
    assert!(matches!(
        features::semantic_features(&audio, &Cancelled),
        Err(AudioError::Cancelled)
    ));
}

#[test]
fn feature_capacity_overflow_and_midflight_cancellation() {
    let audio = pcm(vec![0.; 16000 * 15], 16000);
    let features = features::semantic_features(&audio, &Active).unwrap();
    assert_eq!(features.features.frames(), 749);
    assert!(features::speaker_fbank(&pcm(vec![0.; 16000 * 15 + 1], 16000), &Active).is_err());
    assert!(features::reference_mel(&pcm(vec![1e30; 22050], 22050), &Active).is_err());
    struct CancelDuring(std::cell::Cell<usize>);
    impl SessionControl for CancelDuring {
        fn check(&self) -> Result<()> {
            self.0.set(self.0.get() + 1);
            if self.0.get() >= 4 {
                Err(AudioError::Cancelled)
            } else {
                Ok(())
            }
        }
    }
    assert!(matches!(
        features::speaker_fbank(&audio, &CancelDuring(std::cell::Cell::new(0))),
        Err(AudioError::Cancelled)
    ));
}

#[test]
#[ignore = "requires IRONMLX_REFERENCE_FEATURES generated by tools/reference_features.py"]
fn real_speech_spectrogram_parity() {
    let path = std::env::var("IRONMLX_REFERENCE_FEATURES").unwrap();
    verify_features(&path, &["speech_1s", "speech_odd", "speech_5s"]);
}

#[test]
fn synthetic_reference_spectrogram_parity() {
    verify_features(
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/reference-features.safetensors"
        ),
        &["synthetic"],
    );
}

fn verify_features(path: &str, cases: &[&str]) {
    let (tensors, _) = mlx::io::load_safetensors(path).unwrap();
    for name in cases {
        let audio16 = pcm(tensors[&format!("{name}.wave16")].to_vec().unwrap(), 16000);
        let audio22 = ironmlx_audio::signal::prepare_reference(&audio16, &Active)
            .unwrap()
            .mel_22050;
        let semantic = features::semantic_features(&audio16, &Active).unwrap();
        assert_eq!(
            semantic.attention_mask,
            tensors[&format!("{name}.mask")].to_vec::<i32>().unwrap()
        );
        for (key, actual, max_limit, mean_limit) in [
            (
                "mel",
                features::reference_mel(&audio22, &Active).unwrap(),
                5e-4,
                2e-5,
            ),
            (
                "fbank",
                features::speaker_fbank(&audio16, &Active).unwrap(),
                5e-4,
                3e-5,
            ),
            ("semantic", semantic.features, 1e-4, 1e-5),
        ] {
            let expected = &tensors[&format!("{name}.{key}")];
            assert_eq!(
                expected.shape().as_slice(),
                &[1, actual.frames() as i32, actual.width() as i32]
            );
            let expected = expected.to_vec::<f32>().unwrap();
            let errors: Vec<_> = actual
                .values()
                .iter()
                .zip(&expected)
                .map(|(a, b)| (a - b).abs())
                .collect();
            let maximum = errors.iter().copied().fold(0., f32::max);
            let mean = errors.iter().sum::<f32>() / errors.len() as f32;
            eprintln!("{name}.{key}: max={maximum}, mean={mean}");
            assert!(actual.values().iter().all(|x| x.is_finite()));
            assert!(maximum <= max_limit && mean <= mean_limit, "{name}.{key}");
        }
    }
}
