[package]
name = "mlx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Safe, idiomatic Rust bindings to Apple MLX"

[dependencies]
mlx-sys = { path = "../mlx-sys", version = "0.0.1" }
cxx.workspace = true
thiserror.workspace = true
half = "2"
smallvec = "1"
blocking = "1"

[dev-dependencies]
static_assertions = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
futures-lite = "2"
