#!/usr/bin/env python3
"""Keep the concise bilingual model lists in sync with the App catalogue."""
import argparse
from collections import defaultdict
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "ironmlx-app/Sources/IronMLXAppCore/Resources/supported-models.json"
# Same order and categories as CATALOG_TYPES in the App's Supported models tab.
SECTIONS = (
    ("LLM / VLM", "Language and vision", "语言与视觉", ("text", "vision")),
    ("Audio", "Speech and audio", "音频", ("tts", "audio", "stt")),
    ("Image", "Image generation", "图片生成", ("image",)),
    ("Embedding", "Vector embeddings", "向量", ("embedding",)),
    ("Decision", "Typed decisions", "决策", ("decision",)),
    ("Drafter", "Inference acceleration", "推理加速辅助", ("assistant", "drafter")),
)


def local(en, zh, language):
    return zh if language == "zh" else en


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def repo_link(label, entry):
    return f"[{cell(label)}](https://huggingface.co/{entry['hfRepo']})"


def weight_links(entries):
    affine = [entry for entry in entries if re.fullmatch(r"Affine \d+-bit", entry["weightFormat"])]
    parts = []
    if affine:
        widths = sorted(affine, key=lambda entry: int(re.search(r"\d+", entry["weightFormat"])[0]))
        parts.append("Affine " + "/".join(repo_link(re.search(r"\d+", entry["weightFormat"])[0], entry) for entry in widths) + "-bit")
    parts.extend(repo_link(entry["weightFormat"], entry) for entry in entries if entry not in affine)
    return "; ".join(parts)


def capability(entries, name, language):
    values = {name in entry["capabilities"] for entry in entries}
    if len(values) > 1:
        return local("By variant", "按版本", language)
    return "✓" if True in values else "—"


def helper_main(entry):
    if entry["noteKey"] == "catalog_note_dflash":
        return "Qwen 3.8 27B"
    return re.sub(r"\s+(MTP|Assistant)$", "", entry["name"])


def acceleration(entries, companions):
    name = entries[0]["name"]
    methods = []
    if name.startswith(("Qwen 3.5 ", "Qwen 3.6 ", "Qwen 3.8 ")) and (name, "catalog_note_mtp") in companions:
        methods.append("MTP")
    elif name.startswith("Gemma 4 ") and (name, "catalog_note_gemma_assistant") in companions:
        methods.append("Assistant")
    if name == "Qwen 3.8 27B" and all(entry["weightFormat"] in {"Affine 4-bit", "Affine 8-bit"} for entry in entries):
        methods.append("DFlash2")
    return " / ".join(methods) or "—"


def table(headers, rows):
    return "\n".join(["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"] + ["| " + " | ".join(row) + " |" for row in rows])


def generate(catalog, language):
    groups = defaultdict(list)
    for entry in catalog["entries"]:
        groups[entry["modelId"]].append(entry)
    known_categories = {category for section in SECTIONS for category in section[3]}
    for entries in groups.values():
        if len({entry["name"] for entry in entries}) != 1 or len({entry["category"] for entry in entries}) != 1:
            raise ValueError("A catalogue group must have one name and category")
        if entries[0]["category"] not in known_categories:
            raise ValueError(f"Add the App's new category to SECTIONS: {entries[0]['category']}")
    companions = {(helper_main(entry), entry["noteKey"]) for entry in catalog["entries"] if entry["category"] in {"assistant", "drafter"}}
    if language == "zh":
        lines = ["# 支持的模型", "[English](../supported-models.md)", "<!-- Generated by scripts/build-supported-models-docs.py from the App catalogue. -->", f"与 App **模型 → 模型下载 → 支持的模型** Tab 使用同一清单：**{len(groups)} 个模型 · {len(catalog['entries'])} 个版本**。点击权重格式查看对应仓库。", "✓ 表示能力支持；清单包含已运行验证，以及架构兼容但尚未运行验收的版本。"]
    else:
        lines = ["# Supported models", "[简体中文](zh-CN/supported-models.md)", "<!-- Generated by scripts/build-supported-models-docs.py from the App catalogue. -->", f"The same catalogue as **Models → Model Download → Supported models** in the App: **{len(groups)} models · {len(catalog['entries'])} variants**. Select a weight format to open its repository.", "✓ indicates capability support; the catalogue includes runtime-verified and architecture-compatible variants without runtime acceptance."]
    shortcuts = []
    for title, en_description, zh_description, categories in SECTIONS:
        if any(entries[0]["category"] in categories for entries in groups.values()):
            heading = f"{title} · {local(en_description, zh_description, language)}"
            anchor = re.sub(r"\s+", "-", re.sub(r"[^\w\s-]", "", heading.lower())).strip("-")
            shortcuts.append(f"[{title}](#{anchor})")
    lines.append(" · ".join(shortcuts))
    for title, en_description, zh_description, categories in SECTIONS:
        selected = [entries for entries in groups.values() if entries[0]["category"] in categories]
        if not selected:
            continue
        lines.append(f"## {title} · {local(en_description, zh_description, language)}")
        rows = []
        if title == "LLM / VLM":
            headers = local(["Model", "Type", "Weight formats", "Text", "Images", "Reasoning", "Tools", "Acceleration type"], ["模型名称", "类型", "权重格式", "文本", "图片", "推理", "工具", "加速类型"], language)
            for entries in selected:
                entry = entries[0]
                rows.append([repo_link(entry["name"], entry), "VLM" if entry["category"] == "vision" else "LLM", weight_links(entries), *[capability(entries, name, language) for name in ("text", "vision", "reasoning", "tools")], acceleration(entries, companions)])
            lines.append(table(headers, rows))
            lines.append(local("Images means image understanding. Tools require a compatible native template; the client executes them. Llama 3.2 supports one native custom tool call per turn.", "图片指图片理解；工具调用需要兼容的原生模板，由客户端执行。Llama 3.2 每轮支持一个原生自定义工具调用。", language))
            lines.append(local("Acceleration requires matching auxiliary weights (see Drafter below); — means unsupported or not yet available. DFlash2 requires Qwen 3.8 27B Affine 4/8-bit, is text-only, and cannot run alongside MTP. See [MTP / Assistant](mtp-server-api.md) and [DFlash2](dflash2-server-api.md).", "加速需要匹配的辅助权重，见下方 Drafter 表；— 表示不支持或待支持。DFlash2 仅用于 Qwen 3.8 27B Affine 4/8-bit 的文本请求，与 MTP 互斥。详见 [MTP / Assistant](mtp-server-api.md) / [DFlash2](dflash2-server-api.md)。", language))
        elif title == "Drafter":
            headers = local(["Model", "Type", "Matching main model", "Weight formats"], ["模型名称", "类型", "匹配主模型", "权重格式"], language)
            methods = {"catalog_note_mtp": "MTP", "catalog_note_dflash": "DFlash2", "catalog_note_gemma_assistant": "Gemma Assistant"}
            for entries in selected:
                entry = entries[0]
                rows.append([repo_link(entry["name"], entry), methods[entry["noteKey"]], cell(helper_main(entry)), weight_links(entries)])
            lines.append(table(headers, rows))
            lines.append(local("Auxiliary models cannot run independently. DFlash2 main models require Affine 4/8-bit.", "辅助模型不能独立运行。DFlash2 主模型需为 Affine 4/8-bit。", language))
        else:
            headers = local(["Model", "Type", "Function", "Weight formats"], ["模型名称", "类型", "用途", "权重格式"], language)
            details = {
                "Embedding": ("Embedding", local("Text, image and audio embeddings", "文本、图片与音频向量", language), "text-embeddings.md", "Embedding API", "Embedding API", "text-embeddings.md"),
                "Audio": ("Audio / TTS", local("Speech synthesis", "语音合成", language), "audio-speech-api.md", "speech API", "语音 API", "audio-speech-api.md"),
                "Image": ("Image", local("Text-to-image / single-image editing", "文生图 / 单图编辑", language), "image-generation-api.md", "image generation API", "图片生成 API", "image-generation-api.md"),
                "Decision": ("Decision", "System One API", "laya-systemone-api.md", "Laya guide", "Laya 使用指南", "laya-systemone-api.md"),
            }
            kind, function, guide, en_api, zh_api, api = details[title]
            for entries in selected:
                rows.append([repo_link(entries[0]["name"], entries[0]), kind, f"[{function}]({guide})", weight_links(entries)])
            lines.append(table(headers, rows))
            if title == "Embedding":
                lines.append(local(f"EmbeddingGemma 2 supports BF16 and Affine 4-bit; video inputs are unsupported. See the [{en_api}]({api}) for input formats, dimensions and limits.", f"EmbeddingGemma 2 支持 BF16 与 Affine 4-bit，不支持视频输入。输入格式、维度与限制见[{zh_api}]({api})。", language))
            elif title == "Audio":
                lines.append(local(f"The App prepares additional IndexTTS resources automatically. See the [{en_api}]({api}).", f"IndexTTS 额外资源由 App 自动准备。详见[{zh_api}]({api})。", language))
            elif title == "Image":
                lines.append(local("Qwen Image uses the Qwen Research License, which does not license commercial use. See [model rights](model-license-boundary.md).", "Qwen Image 受 Qwen Research License 约束，不授权商业用途。详见[模型许可边界](model-license-boundary.md)。", language))
    lines.append("## " + local("Before downloading", "下载前须知", language))
    lines.append(local("Choose a version that fits your memory; context, concurrency, and assistants add to weight memory. FP16/BF16 are unquantized weight types. OptiQ and mixed-bit entries do not use one precision for every layer.", "按可用内存选择版本，上下文、并发与辅助模型会增加内存需求。FP16/BF16 为未量化权重；OptiQ 与混合位宽模型并非所有层使用同一精度。", language))
    lines.append(local("[Download and update](user-guide.md#download-and-update-models) · [Model loading](troubleshooting.md#model-loading) · [API compatibility](text-vision-api.md#api-compatibility-and-limits) · [Model rights](model-license-boundary.md)", "[下载与更新](user-guide.md#下载与更新模型) · [模型加载排查](troubleshooting.md#模型加载) · [API 兼容性](text-vision-api.md#api-兼容性与限制) · [模型许可](model-license-boundary.md)", language))
    return "\n\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in model lists differ from the App catalogue")
    args = parser.parse_args()
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    stale = []
    for language, directory in (("en", ROOT / "docs"), ("zh", ROOT / "docs/zh-CN")):
        path = directory / "supported-models.md"
        content = generate(catalog, language)
        if args.check:
            if path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        parser.exit(1, "Model lists are stale; run scripts/build-supported-models-docs.py: " + ", ".join(stale) + "\n")
    print("Model lists match the App catalogue." if args.check else "Updated bilingual model lists from the App catalogue.")


if __name__ == "__main__":
    main()
