#!/usr/bin/env bash
#
# setup-mlx.sh — build + install the MLX C++ static lib for ironmlx, backfilling
# the private transitive `libgguflib.a` that MLX's `make install` omits, and
# emitting a sourceable env file. See docs/mlx-setup.md for the full rationale.
#
# Usage:
#   MLX_SRC=<mlx-source> MLX_PREFIX=<install-prefix> scripts/setup-mlx.sh
#
# Env (all optional; defaults shown):
#   MLX_SRC     MLX source checkout            (default: /Users/xin/workspace/iron-rivals/mlx)
#   MLX_PREFIX  install prefix                 (default: $HOME/.local/mlx)
#   JOBS        parallel build jobs            (default: all CPUs)
#
# After it finishes, source the printed env file in any shell that builds/runs
# ironmlx:  source "$MLX_PREFIX/mlx-env.sh"
#
# Apple Silicon macOS only.

set -euo pipefail

MLX_SRC="${MLX_SRC:-/Users/xin/workspace/iron-rivals/mlx}"
MLX_PREFIX="${MLX_PREFIX:-$HOME/.local/mlx}"
JOBS="${JOBS:-$(sysctl -n hw.ncpu)}"
BUILD_DIR="$MLX_SRC/build"

if [ ! -d "$MLX_SRC" ]; then
  echo "error: MLX_SRC not found: $MLX_SRC" >&2
  exit 1
fi

echo "==> Configure MLX (static, Metal)  src=$MLX_SRC  prefix=$MLX_PREFIX"
cmake -S "$MLX_SRC" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=OFF \
  -DMLX_BUILD_METAL=ON \
  -DMLX_METAL_JIT=OFF \
  -DMLX_BUILD_TESTS=OFF \
  -DMLX_BUILD_EXAMPLES=OFF \
  -DMLX_BUILD_BENCHMARKS=OFF \
  -DMLX_BUILD_PYTHON_BINDINGS=OFF \
  -DCMAKE_INSTALL_PREFIX="$MLX_PREFIX"

echo "==> Build MLX (-j$JOBS)"
cmake --build "$BUILD_DIR" -j "$JOBS"

echo "==> Install MLX -> $MLX_PREFIX"
cmake --install "$BUILD_DIR"

# MLX's install does NOT export the private transitive `libgguflib.a` (GGUF
# support). `libmlx.a` references its `_gguf_*` symbols, and mlx-sys/build.rs
# auto-links every lib*.a in $MLX_DIR/lib — so without this, anything linking
# GGUF (e.g. the `mlx` crate's p2c_io test) fails with `Undefined symbols:
# _gguf_open ...`. Backfill it. (libjaccl.a + mlx.metallib ARE installed.)
echo "==> Backfill libgguflib.a (omitted by MLX install)"
GGUF_A="$BUILD_DIR/mlx/io/libgguflib.a"
if [ ! -f "$GGUF_A" ]; then
  echo "error: libgguflib.a not found at $GGUF_A (build did not produce it?)" >&2
  exit 1
fi
cp -v "$GGUF_A" "$MLX_PREFIX/lib/"

echo "==> Sanity check"
sane=1
for f in include/mlx/array.h lib/libmlx.a lib/libgguflib.a lib/mlx.metallib; do
  if [ -e "$MLX_PREFIX/$f" ]; then
    echo "    ok: $f"
  else
    echo "    MISSING: $f" >&2
    sane=0
  fi
done
[ "$sane" -eq 1 ] || { echo "error: install incomplete" >&2; exit 1; }

ENV_FILE="$MLX_PREFIX/mlx-env.sh"
cat > "$ENV_FILE" <<EOF
# MLX env for ironmlx build/run. Generated by scripts/setup-mlx.sh — source me.
export MLX_ROOT="$MLX_PREFIX"
export MLX_DIR="\$MLX_ROOT"
export MLX_METAL_PATH="\$MLX_ROOT/lib"
export DYLD_LIBRARY_PATH="\$MLX_ROOT/lib\${DYLD_LIBRARY_PATH:+:\$DYLD_LIBRARY_PATH}"
EOF

echo
echo "==> Done. MLX installed at: $MLX_PREFIX"
echo "    Source the env in each shell that builds/runs ironmlx:"
echo "        source \"$ENV_FILE\""
echo "    Then:  cargo build --release  /  cargo test --all-features --workspace"
