//! Gemma4 unified parity harness.
//!
//! Fixtures are generated by `tests/fixtures/gemma4_unified/gen_fixture.py`
//! using mlx-vlm's `gemma4_unified` reference implementation. Tests are
//! ignored because they require the 12B checkpoint and generated fixture files.

use std::path::{Path, PathBuf};

use ironmlx::core::generate::build_position_ids;
use ironmlx::core::scheduler::DenseVlMethods;
use ironmlx::core::{Loader, Model};
use ironmlx::models::gemma4::image_processor::preprocess;
use ironmlx::models::gemma4::{Gemma4Config, Gemma4Model};
use mlx::{Array, Dtype, StreamOrDevice};

const FIXTURE_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/gemma4_unified");
const COCO_IMAGE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/p6_qwen35_vl/coco_sample.jpg"
);
const IMAGE_TOKEN_ID: i32 = 258880;
// MLX-VLM and ironmlx run the same 4-bit checkpoint through different fused
// kernels. Greedy and top-5 tokens are exact; the full-vocab max_abs guards
// against large regressions without requiring bit-identical logits.
const TEXT_LOGIT_MAX_ABS_LIMIT: f32 = 5.5;
const VISION_LOGIT_MAX_ABS_LIMIT: f32 = 4.5;

fn default_snapshot_dir() -> Option<PathBuf> {
    if let Ok(path) = std::env::var("GEMMA4_UNIFIED_MODEL") {
        let path = PathBuf::from(path);
        if path.exists() {
            return Some(path);
        }
        eprintln!("GEMMA4_UNIFIED_MODEL={} does not exist", path.display());
        return None;
    }
    let home = std::env::var("HOME").ok()?;
    let snapshots = PathBuf::from(home)
        .join(".ironmlx/models/models--mlx-community--gemma-4-12B-it-4bit/snapshots");
    std::fs::read_dir(snapshots)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .find(|path| path.is_dir())
}

fn checkpoint_dir() -> Option<PathBuf> {
    default_snapshot_dir()
}

fn fixture_path(name: &str) -> PathBuf {
    Path::new(FIXTURE_DIR).join(name)
}

fn load_npy(name: &str) -> Array {
    let path = fixture_path(name);
    mlx::io::load_npy(path.to_str().expect("utf8 path"))
        .unwrap_or_else(|e| panic!("failed to load {}: {e}", path.display()))
}

fn maybe_fixture(name: &str) -> bool {
    fixture_path(name).exists()
}

fn to_f32_vec(arr: &Array) -> Vec<f32> {
    mlx::ops::cast::astype(arr, Dtype::Float32)
        .expect("astype f32")
        .to_vec()
        .expect("to_vec")
}

fn max_abs_diff(a: &Array, b: &Array) -> f32 {
    let av = to_f32_vec(a);
    let bv = to_f32_vec(b);
    assert_eq!(av.len(), bv.len(), "element count mismatch");
    av.iter()
        .zip(bv.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

fn greedy_argmax(arr: &Array) -> usize {
    let v = to_f32_vec(arr);
    v.iter()
        .enumerate()
        .max_by(|a, b| a.1.partial_cmp(b.1).unwrap_or(std::cmp::Ordering::Equal))
        .map(|(idx, _)| idx)
        .expect("non-empty logits")
}

fn top_k(arr: &Array, k: usize) -> Vec<usize> {
    let v = to_f32_vec(arr);
    let mut idx: Vec<usize> = (0..v.len()).collect();
    idx.sort_by(|&a, &b| v[b].partial_cmp(&v[a]).unwrap_or(std::cmp::Ordering::Equal));
    idx.truncate(k);
    idx
}

fn flatten_logits(logits: &Array) -> Array {
    let dims = logits.shape();
    let vocab = *dims.as_slice().last().expect("logits rank > 0");
    logits.reshape((vocab,)).expect("reshape logits")
}

fn last_hidden_slice(hidden: &Array) -> Array {
    let dims = hidden.shape();
    let dims = dims.as_slice();
    assert_eq!(dims.len(), 3, "hidden must be [B,S,H], got {dims:?}");
    let (b, s, h) = (dims[0], dims[1], dims[2]);
    mlx::ops::indexing::slice_strided(
        hidden,
        &[0_i32, s - 1, 0][..],
        &[b, s, h][..],
        &[1_i32, 1, 1][..],
    )
    .expect("slice last hidden")
    .reshape((b, h))
    .expect("reshape last hidden")
}

fn report_array_diff(label: &str, got: &Array, expected: &Array, max_abs_limit: f32) {
    assert_eq!(
        got.shape().as_slice(),
        expected.shape().as_slice(),
        "{label}: shape mismatch"
    );
    let got_values = to_f32_vec(got);
    let expected_values = to_f32_vec(expected);
    let signed: Vec<f32> = got_values
        .iter()
        .zip(expected_values.iter())
        .map(|(a, b)| a - b)
        .collect();
    let err = signed.iter().map(|d| d.abs()).fold(0.0_f32, f32::max);
    let mean = signed.iter().map(|&x| x as f64).sum::<f64>() / signed.len() as f64;
    let mut diff_idx: Vec<(usize, f32)> = signed
        .iter()
        .enumerate()
        .map(|(idx, &d)| (idx, d.abs()))
        .collect();
    diff_idx.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    let top_diff = diff_idx
        .iter()
        .take(5)
        .map(|&(idx, diff)| (idx, got_values[idx], expected_values[idx], diff))
        .collect::<Vec<_>>();
    eprintln!("{label}: max_abs={err:.6} mean={mean:.6} top_diff={top_diff:?}");
    assert!(
        err < max_abs_limit,
        "{label}: max_abs {err} >= {max_abs_limit}"
    );
}

fn slice_layer_row(layers: &Array, row: i32) -> Array {
    let dims = layers.shape();
    let dims = dims.as_slice();
    assert_eq!(dims.len(), 2, "layer fixture must be [L,H], got {dims:?}");
    mlx::ops::indexing::slice_strided(
        layers,
        &[row, 0][..],
        &[row + 1, dims[1]][..],
        &[1_i32, 1][..],
    )
    .expect("slice layer row")
}

fn report_layer_trace(label: &str, got: &[Array], expected_name: &str) {
    let expected = load_npy(expected_name);
    let dims = expected.shape();
    let dims = dims.as_slice();
    assert_eq!(dims.len(), 2, "{label}: expected trace must be [L,H]");
    assert_eq!(got.len(), dims[0] as usize, "{label}: layer count mismatch");
    for (idx, layer) in got.iter().enumerate() {
        let expected_row = slice_layer_row(&expected, idx as i32);
        let err = max_abs_diff(layer, &expected_row);
        eprintln!("{label} layer {idx:02}: max_abs={err:.6}");
    }
}

fn report_expected_final_norm(
    label: &str,
    loader: &Loader,
    eps: f32,
    trace_name: &str,
    hidden_name: &str,
) {
    let expected_trace = load_npy(trace_name);
    let dims = expected_trace.shape();
    let dims = dims.as_slice();
    assert_eq!(dims.len(), 2, "{label}: expected trace must be [L,H]");
    let expected_pre_final = slice_layer_row(&expected_trace, dims[0] - 1);
    let norm_weight = loader
        .tensor("model.norm.weight")
        .expect("model.norm.weight");
    let normalized =
        mlx::fast::rms_norm(&expected_pre_final, Some(norm_weight), eps).expect("final rms_norm");
    report_array_diff(label, &normalized, &load_npy(hidden_name), 1.0);
}

fn compare_logits(label: &str, got: &Array, expected: &Array, max_abs_limit: f32) {
    let got_flat = flatten_logits(got);
    let expected_flat = flatten_logits(expected);
    assert_eq!(
        got_flat.shape().as_slice(),
        expected_flat.shape().as_slice(),
        "{label}: logits shape mismatch"
    );
    let got_argmax = greedy_argmax(&got_flat);
    let expected_argmax = greedy_argmax(&expected_flat);
    let got_top5 = top_k(&got_flat, 5);
    let expected_top5 = top_k(&expected_flat, 5);
    let err = max_abs_diff(&got_flat, &expected_flat);
    let got_values = to_f32_vec(&got_flat);
    let expected_values = to_f32_vec(&expected_flat);
    let signed: Vec<f32> = got_values
        .iter()
        .zip(expected_values.iter())
        .map(|(a, b)| a - b)
        .collect();
    let mean = signed.iter().map(|&x| x as f64).sum::<f64>() / signed.len() as f64;
    let mut sorted = signed.clone();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let median = sorted[sorted.len() / 2];
    let residual_max = signed
        .iter()
        .map(|&x| (x as f64 - mean).abs() as f32)
        .fold(0.0_f32, f32::max);
    let mut diff_idx: Vec<(usize, f32)> = signed
        .iter()
        .enumerate()
        .map(|(idx, &d)| (idx, d.abs()))
        .collect();
    diff_idx.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    let top_diff = diff_idx
        .iter()
        .take(5)
        .map(|&(idx, diff)| (idx, got_values[idx], expected_values[idx], diff))
        .collect::<Vec<_>>();
    eprintln!(
        "{label}: argmax got={got_argmax} expected={expected_argmax} \
         max_abs={err:.4} mean={mean:.6} median={median:.6} residual_max={residual_max:.4} \
         got_top5={got_top5:?} expected_top5={expected_top5:?} top_diff={top_diff:?}"
    );

    assert_eq!(
        got_argmax, expected_argmax,
        "{label}: greedy argmax mismatch"
    );
    let got_set: std::collections::BTreeSet<usize> = got_top5.iter().copied().collect();
    let expected_set: std::collections::BTreeSet<usize> = expected_top5.iter().copied().collect();
    assert_eq!(got_set, expected_set, "{label}: top-5 token set mismatch");
    assert!(
        err < max_abs_limit,
        "{label}: max_abs {err} >= {max_abs_limit}"
    );
}

fn parity_diag_enabled() -> bool {
    std::env::var_os("GEMMA4_UNIFIED_PARITY_DIAG").is_some()
}

fn load_ids(name: &str) -> Vec<i32> {
    load_npy(name).to_vec().expect("ids to_vec")
}

fn ids_array(ids: &[i32]) -> Array {
    (ids, &[1_i32, ids.len() as i32][..])
        .try_into()
        .expect("input_ids")
}

fn split_image_pixel_values(arr: &Array) -> Vec<Array> {
    let dims = arr.shape();
    let dims = dims.as_slice();
    assert_eq!(
        dims.len(),
        3,
        "vision_pixel_values.npy must be [I,N,D], got {dims:?}"
    );
    let (images, n, d) = (dims[0], dims[1], dims[2]);
    (0..images)
        .map(|row| {
            mlx::ops::indexing::slice_strided(
                arr,
                &[row, 0, 0][..],
                &[row + 1, n, d][..],
                &[1_i32, 1, 1][..],
            )
            .expect("slice pixel_values row")
        })
        .collect()
}

fn load_grids() -> Vec<(i32, i32, i32)> {
    let arr = load_npy("vision_grid_thw.npy");
    let values: Vec<i32> = arr.to_vec().expect("grid to_vec");
    values
        .chunks_exact(3)
        .map(|chunk| (chunk[0], chunk[1], chunk[2]))
        .collect()
}

#[test]
#[ignore = "requires generated Gemma4 unified fixtures"]
fn gemma4_unified_preprocess_matches_mlx_vlm_fixture() {
    if !maybe_fixture("vision_pixel_values.npy") {
        eprintln!("skip: generate Gemma4 unified fixtures first");
        return;
    }
    let Some(dir) = checkpoint_dir() else {
        eprintln!("skip: no Gemma4 unified checkpoint");
        return;
    };

    let loader = Loader::open_multimodal(&dir).expect("Loader::open_multimodal");
    let cfg = Gemma4Config::from_loader(&loader).expect("Gemma4Config");
    let vision_config = cfg.vision_config.as_ref().expect("vision_config");
    let bytes = std::fs::read(COCO_IMAGE).expect("read coco fixture");
    let processed = preprocess(&bytes, vision_config).expect("preprocess");

    let expected = load_npy("vision_pixel_values.npy");
    let expected_dims = expected.shape();
    assert_eq!(
        expected_dims.as_slice()[0],
        1,
        "fixture should contain one image"
    );
    assert_eq!(
        processed.pixel_values.shape().as_slice(),
        &[1, expected_dims.as_slice()[1], expected_dims.as_slice()[2]],
        "pixel_values shape mismatch"
    );
    let grids = load_grids();
    assert_eq!(grids.len(), 1);
    assert_eq!(
        (1, processed.grid_h, processed.grid_w),
        grids[0],
        "grid_thw mismatch"
    );

    let err = max_abs_diff(&processed.pixel_values, &expected);
    eprintln!("gemma4 unified preprocess max_abs={err:.6}");
    assert!(
        err < 0.03,
        "preprocess pixel max_abs {err} exceeds JPEG decode floor / PIL bicubic tolerance"
    );
}

#[test]
#[ignore = "requires generated Gemma4 unified fixtures and 12B weights"]
fn gemma4_unified_text_logits_match_mlx_vlm_reference() {
    if !maybe_fixture("text_expected_last_logits.npy") {
        eprintln!("skip: generate Gemma4 unified fixtures first");
        return;
    }
    let Some(dir) = checkpoint_dir() else {
        eprintln!("skip: no Gemma4 unified checkpoint");
        return;
    };

    let loader = Loader::open(&dir).expect("Loader::open");
    let model = Gemma4Model::from_loader(&loader).expect("Gemma4Model::from_loader");
    let ids = load_ids("text_input_ids.npy");
    let s = ids.len() as i32;
    let input_ids = ids_array(&ids);
    let pos = build_position_ids(0, s).expect("position_ids");
    let mut cache = Model::make_cache(&model, 1, s + 1, model.cache_dtype()).expect("make_cache");
    let logits = Model::forward_on(
        &model,
        &input_ids,
        &pos,
        None,
        None,
        Some(&mut cache),
        StreamOrDevice::default(),
    )
    .expect("forward_on");
    let expected = load_npy("text_expected_last_logits.npy");
    if parity_diag_enabled() {
        let trace = model
            .forward_text_layer_last_trace_on(&input_ids, StreamOrDevice::default())
            .expect("forward text layer trace");
        report_layer_trace(
            "gemma4 unified text pre-norm trace",
            &trace,
            "text_expected_layer_last_hiddens.npy",
        );
        let stage_trace = model
            .forward_text_layer0_stage_last_trace_on(&input_ids, StreamOrDevice::default())
            .expect("forward text layer0 stage trace");
        report_layer_trace(
            "gemma4 unified text layer0 stage trace",
            &stage_trace,
            "text_expected_layer0_stage_last_hiddens.npy",
        );
        report_expected_final_norm(
            "gemma4 unified text final norm on reference pre-final",
            &loader,
            model.text().config().rms_norm_eps,
            "text_expected_layer_last_hiddens.npy",
            "text_expected_last_hidden.npy",
        );
        let no_cache_hidden = Model::forward_text_hidden(
            &model,
            &input_ids,
            &pos,
            None,
            None,
            None,
            StreamOrDevice::default(),
        )
        .expect("forward_text_hidden no-cache");
        let no_cache_last_hidden = last_hidden_slice(&no_cache_hidden);
        report_array_diff(
            "gemma4 unified text hidden",
            &no_cache_last_hidden,
            &load_npy("text_expected_last_hidden.npy"),
            f32::INFINITY,
        );
        let no_cache_raw_logits = model
            .text()
            .as_output_on(&no_cache_last_hidden, StreamOrDevice::default())
            .expect("text raw logits");
        report_array_diff(
            "gemma4 unified text raw logits",
            &no_cache_raw_logits,
            &load_npy("text_expected_last_raw_logits.npy"),
            f32::INFINITY,
        );
        let no_cache_logits = Model::forward_on(
            &model,
            &input_ids,
            &pos,
            None,
            None,
            None,
            StreamOrDevice::default(),
        )
        .expect("forward_on no-cache");
        compare_logits(
            "gemma4 unified text no-cache",
            &no_cache_logits,
            &expected,
            10.0,
        );
    }
    compare_logits(
        "gemma4 unified text",
        &logits,
        &expected,
        TEXT_LOGIT_MAX_ABS_LIMIT,
    );
}

#[test]
#[ignore = "requires generated Gemma4 unified fixtures and 12B weights"]
fn gemma4_unified_vision_logits_match_mlx_vlm_reference() {
    if !maybe_fixture("vision_expected_last_logits.npy") {
        eprintln!("skip: generate Gemma4 unified fixtures first");
        return;
    }
    let Some(dir) = checkpoint_dir() else {
        eprintln!("skip: no Gemma4 unified checkpoint");
        return;
    };

    let loader = Loader::open_multimodal(&dir).expect("Loader::open_multimodal");
    let model = Gemma4Model::from_loader(&loader).expect("Gemma4Model::from_loader");
    let ids = load_ids("vision_input_ids.npy");
    let image_tokens = ids.iter().filter(|&&id| id == IMAGE_TOKEN_ID).count() as i32;
    let s = ids.len() as i32;
    let input_ids = ids_array(&ids);
    let pixel_values = split_image_pixel_values(&load_npy("vision_pixel_values.npy"));
    let grids = load_grids();
    let vision_embeds = model
        .compute_vision_embeds(&pixel_values, &grids, StreamOrDevice::default())
        .expect("compute_vision_embeds");
    assert_eq!(
        vision_embeds.shape().as_slice()[0],
        image_tokens,
        "vision embed rows must match image token count"
    );

    let dummy_pos = build_position_ids(0, 1).expect("dummy position_ids");
    let mut cache = Model::make_cache(&model, 1, s + 1, model.cache_dtype()).expect("make_cache");
    let logits = model
        .forward_vl_chunk(
            &input_ids,
            &dummy_pos,
            Some(&[s]),
            None,
            Some(&mut cache),
            Some(&vision_embeds),
            IMAGE_TOKEN_ID,
            StreamOrDevice::default(),
        )
        .expect("forward_vl_chunk");
    let expected = load_npy("vision_expected_last_logits.npy");
    if parity_diag_enabled() {
        report_expected_final_norm(
            "gemma4 unified vision final norm on reference pre-final",
            &loader,
            model.text().config().rms_norm_eps,
            "vision_expected_layer_last_hiddens.npy",
            "vision_expected_last_hidden.npy",
        );
        let no_cache_hidden = model
            .forward_vl_hidden(
                &input_ids,
                &dummy_pos,
                Some(&[s]),
                None,
                None,
                Some(&vision_embeds),
                IMAGE_TOKEN_ID,
                StreamOrDevice::default(),
            )
            .expect("forward_vl_hidden no-cache");
        let no_cache_last_hidden = last_hidden_slice(&no_cache_hidden);
        report_array_diff(
            "gemma4 unified vision hidden",
            &no_cache_last_hidden,
            &load_npy("vision_expected_last_hidden.npy"),
            f32::INFINITY,
        );
        let no_cache_raw_logits = model
            .text()
            .as_output_on(&no_cache_last_hidden, StreamOrDevice::default())
            .expect("vision raw logits");
        report_array_diff(
            "gemma4 unified vision raw logits",
            &no_cache_raw_logits,
            &load_npy("vision_expected_last_raw_logits.npy"),
            f32::INFINITY,
        );
        let no_cache_logits = model
            .forward_vl_chunk(
                &input_ids,
                &dummy_pos,
                Some(&[s]),
                None,
                None,
                Some(&vision_embeds),
                IMAGE_TOKEN_ID,
                StreamOrDevice::default(),
            )
            .expect("forward_vl_chunk no-cache");
        compare_logits(
            "gemma4 unified vision no-cache",
            &no_cache_logits,
            &expected,
            10.0,
        );
    }
    compare_logits(
        "gemma4 unified vision",
        &logits,
        &expected,
        VISION_LOGIT_MAX_ABS_LIMIT,
    );
}
