//! P3b4 Mtp numerical-correctness integration test.
//!
//! Loads `.npy` fixtures from `tests/fixtures/mtp/` (generated by
//! `gen_fixture.py` against an independent Python reference of vllm-mlx's
//! `_MTPModule.mtp_forward`) and verifies that `nn::Mtp::forward` produces
//! numerically equivalent output.
//!
//! Tolerance: `atol = 1e-3` against the fp32-promoted reference, in line
//! with bf16 rounding limits in the matmul stages.
//!
//! Regenerate fixtures via:
//!
//! ```text
//! cd ironmlx/tests/fixtures/mtp && python gen_fixture.py
//! ```

use mlx::{Array, Dtype};

use ironmlx::nn::{
    DecoderLayer, DecoderLayerConfig, GatedAttention, GatedAttentionConfig, Linear, Mlp, Mrope,
    Mtp, MtpConfig, RmsNorm,
};

const FIXTURE_DIR: &str = "tests/fixtures/mtp";

const HIDDEN: i32 = 32;
const HQ: i32 = 4;
const HKV: i32 = 2;
const D: i32 = 8;
const INTERMEDIATE: i32 = 64;
const RMS_EPS: f32 = 1e-6;

fn load(name: &str) -> Array {
    let path = format!("{FIXTURE_DIR}/{name}.npy");
    mlx::io::load_npy(&path).unwrap_or_else(|e| panic!("failed to load {path}: {e}"))
}

/// max(|a - b|) for arrays cast to fp32.
fn max_abs_diff(a: &Array, b: &Array) -> f32 {
    let a32 = mlx::ops::cast::astype(a, Dtype::Float32).unwrap();
    let b32 = mlx::ops::cast::astype(b, Dtype::Float32).unwrap();
    let av: Vec<f32> = a32.to_vec().unwrap();
    let bv: Vec<f32> = b32.to_vec().unwrap();
    assert_eq!(av.len(), bv.len(), "shape mismatch");
    av.iter()
        .zip(bv.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

#[test]
fn mtp_forward_matches_python_fixture() {
    // Load top-level Mtp weights.
    let pre_fc_h_w = load("pre_fc_norm_hidden_weight");
    let pre_fc_e_w = load("pre_fc_norm_embedding_weight");
    let fc_w = load("fc_weight");
    let mtp_norm_w = load("norm_weight");

    // Load layer 0 weights.
    let in_ln_w = load("layer0_input_layernorm_weight");
    let q_w = load("layer0_q_proj_weight");
    let k_w = load("layer0_k_proj_weight");
    let v_w = load("layer0_v_proj_weight");
    let o_w = load("layer0_o_proj_weight");
    let q_norm_w = load("layer0_q_norm_weight");
    let k_norm_w = load("layer0_k_norm_weight");
    let post_ln_w = load("layer0_post_attention_layernorm_weight");
    let gate_w = load("layer0_mlp_gate_proj_weight");
    let up_w = load("layer0_mlp_up_proj_weight");
    let down_w = load("layer0_mlp_down_proj_weight");

    let layer_cfg = DecoderLayerConfig {
        hidden_size: HIDDEN,
        intermediate_size: INTERMEDIATE,
        num_heads: HQ,
        num_kv_heads: HKV,
        head_dim: D,
        rms_norm_eps: RMS_EPS,
        attention_bias: false,
        linear_num_value_heads: 0,
        linear_num_key_heads: 0,
        linear_key_head_dim: 0,
        linear_value_head_dim: 0,
        linear_conv_kernel_dim: 0,
    };

    let attn = GatedAttention::from_components(
        Linear::new_fp(q_w, None),
        Linear::new_fp(k_w, None),
        Linear::new_fp(v_w, None),
        Linear::new_fp(o_w, None),
        RmsNorm::new(q_norm_w, RMS_EPS),
        RmsNorm::new(k_norm_w, RMS_EPS),
        GatedAttentionConfig {
            num_heads: HQ,
            num_kv_heads: HKV,
            head_dim: D,
            rms_norm_eps: RMS_EPS,
            attention_bias: false,
        },
    );

    let mlp = Mlp::from_components(
        Linear::new_fp(gate_w, None),
        Linear::new_fp(up_w, None),
        Linear::new_fp(down_w, None),
    );

    let layer0 = DecoderLayer::from_components_full(
        RmsNorm::new(in_ln_w, RMS_EPS),
        attn,
        RmsNorm::new(post_ln_w, RMS_EPS),
        mlp,
        layer_cfg,
    );

    let cfg = MtpConfig {
        hidden_size: HIDDEN,
        num_mtp_layers: 1,
        layer: layer_cfg,
    };

    let mtp = Mtp::from_components(
        RmsNorm::new(pre_fc_h_w, RMS_EPS),
        RmsNorm::new(pre_fc_e_w, RMS_EPS),
        Linear::new_fp(fc_w, None),
        vec![layer0],
        RmsNorm::new(mtp_norm_w, RMS_EPS),
        cfg,
    );

    // Inputs + precomputed mrope tables.
    let hidden = load("input_hidden");
    let next_embeds = load("input_next_embeds");
    let cos = load("expected_cos");
    let sin = load("expected_sin");
    let expected = load("expected_mtp_out");

    // Mrope is reconstructed (the Rust path lazy-builds inv_freq + position_ids from
    // config) — but at forward time only the (cos, sin) tables are consumed, and we
    // load them from the fixture to bit-match the Python reference.
    let mrope = Mrope::new(D, 1e7, 1.0, &[2, 1, 1], true).unwrap();

    let out = mtp
        .forward(&hidden, &next_embeds, &mrope, &cos, &sin, None, None)
        .expect("forward");

    assert_eq!(out.shape().as_slice(), expected.shape().as_slice());
    assert_eq!(out.shape().as_slice(), &[1, 4, HIDDEN]);
    // expected dtype is fp32 (all RmsNorm weights in this fixture are fp32 → final
    // mtp.norm output is fp32). If a future fixture changes that, update accordingly.
    assert_eq!(out.dtype(), Dtype::Float32);
    assert_eq!(expected.dtype(), Dtype::Float32);

    // If this fails: check (a) concat order [e, h] vs [h, e]; (b) fc_weight shape
    // [H, 2H]; (c) rms_norm_eps is 1e-6 at all call sites. See plan Step 4.5.
    let err = max_abs_diff(&out, &expected);
    assert!(err < 1e-3, "Mtp output max abs diff = {err} > 1e-3");
}
