//! P3b1 MRoPE numerical-correctness integration tests.
//!
//! Loads .npy fixtures from `tests/fixtures/p3b1_mrope/` (generated by
//! `gen_fixture.py` against an independent Python MRoPE reference) and
//! verifies that our `Mrope::cos_sin` and `Mrope::apply` produce
//! numerically equivalent results.
//!
//! Tolerances:
//!   - cos/sin (fp32): atol = 1e-5
//!   - apply (bf16):   atol = 1e-3 (limited by bf16 rounding)

use mlx::{Array, Dtype};

use ironmlx::nn::Mrope;

const FIXTURE_DIR: &str = "tests/fixtures/p3b1_mrope";

fn load(name: &str) -> Array {
    let path = format!("{FIXTURE_DIR}/{name}.npy");
    mlx::io::load_npy(&path).unwrap_or_else(|e| panic!("failed to load {path}: {e}"))
}

/// max(|a - b|) for fp32 arrays of equal shape.
fn max_abs_diff_f32(a: &Array, b: &Array) -> f32 {
    let av: Vec<f32> = a.to_vec().unwrap();
    let bv: Vec<f32> = b.to_vec().unwrap();
    assert_eq!(av.len(), bv.len(), "shape mismatch");
    av.iter()
        .zip(bv.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max)
}

/// max(|a - b|) where both arrays are bf16; cast to fp32 for the diff.
fn max_abs_diff_bf16(a: &Array, b: &Array) -> f32 {
    let a32 = mlx::ops::cast::astype(a, Dtype::Float32).unwrap();
    let b32 = mlx::ops::cast::astype(b, Dtype::Float32).unwrap();
    max_abs_diff_f32(&a32, &b32)
}

#[test]
fn cos_sin_matches_python_fixture() {
    // head_dim=256, partial=0.25 -> rot_dim=64, half=32, sections=[11,11,10].
    let mrope = Mrope::new(256, 1e7, 0.25, &[11, 11, 10], true).unwrap();

    let pos = load("input_position_ids");
    let exp_cos = load("expected_cos");
    let exp_sin = load("expected_sin");

    let (cos, sin) = mrope.cos_sin(&pos).expect("cos_sin");

    assert_eq!(cos.shape().as_slice(), exp_cos.shape().as_slice());
    assert_eq!(sin.shape().as_slice(), exp_sin.shape().as_slice());

    let cos_err = max_abs_diff_f32(&cos, &exp_cos);
    let sin_err = max_abs_diff_f32(&sin, &exp_sin);
    assert!(cos_err < 1e-5, "cos max abs diff = {cos_err} > 1e-5");
    assert!(sin_err < 1e-5, "sin max abs diff = {sin_err} > 1e-5");
}

#[test]
fn apply_matches_python_fixture() {
    let mrope = Mrope::new(256, 1e7, 0.25, &[11, 11, 10], true).unwrap();

    let q = load("input_q");
    let k = load("input_k");
    let cos = load("expected_cos"); // reuse -- these are the inputs to apply
    let sin = load("expected_sin");
    let exp_q_rot = load("expected_q_rot");
    let exp_k_rot = load("expected_k_rot");

    let (q_rot, k_rot) = mrope.apply(&q, &k, &cos, &sin).expect("apply");

    assert_eq!(q_rot.shape().as_slice(), exp_q_rot.shape().as_slice());
    assert_eq!(k_rot.shape().as_slice(), exp_k_rot.shape().as_slice());
    assert_eq!(q_rot.dtype(), Dtype::Bfloat16);
    assert_eq!(k_rot.dtype(), Dtype::Bfloat16);

    let q_err = max_abs_diff_bf16(&q_rot, &exp_q_rot);
    let k_err = max_abs_diff_bf16(&k_rot, &exp_k_rot);
    assert!(q_err < 1e-3, "q_rot max abs diff = {q_err} > 1e-3");
    assert!(k_err < 1e-3, "k_rot max abs diff = {k_err} > 1e-3");
}

#[test]
fn rotary_plus_sdpa_matches_fixture() {
    // End-to-end check: Mrope::apply -> SDPA, with input q/k/v from the
    // fixture, against expected_attn_out. This validates the whole MRoPE +
    // SDPA path the way Attention::forward will run it.
    let mrope = Mrope::new(256, 1e7, 0.25, &[11, 11, 10], true).unwrap();

    let q = load("input_q");
    let k = load("input_k");
    let v = load("input_v");
    let cos = load("expected_cos");
    let sin = load("expected_sin");
    let expected = load("expected_attn_out");

    let (q_rot, k_rot) = mrope.apply(&q, &k, &cos, &sin).expect("apply");

    let head_dim = 256_f32;
    let scale = 1.0 / head_dim.sqrt();
    let out =
        mlx::fast::scaled_dot_product_attention(&q_rot, &k_rot, &v, scale, "causal", None, None)
            .expect("sdpa");

    assert_eq!(out.shape().as_slice(), expected.shape().as_slice());
    let err = max_abs_diff_bf16(&out, &expected);
    assert!(err < 1e-3, "rotary+sdpa max abs diff = {err} > 1e-3");
}
