//! P6.7 VL chunked prefill — bit-identical equivalence test.
//!
//! Drives `GenerationStream` (which owns the chunking loop) across 3
//! `prefill_chunk_size` values (0, 256, 64) and asserts the first
//! decoded token matches the P6.6 baseline (expected first token from
//! `expected_first_token.txt`, typically 760).
//!
//! The fixture lives in `tests/fixtures/p6_qwen35_vl/multi_image/` and is
//! regenerated by `run_p6_6_diff.sh` (N=2 or N=3 selected by env).
//!
//! Run with:
//! ```text
//! QWEN35_MODEL=/path/to/Qwen3.5-4B-MLX-4bit \
//! MLX_DIR=$HOME/.local/mlx \
//! cargo test -p ironmlx --release --test p6_7_chunked_prefill -- --ignored --nocapture
//! ```

use std::path::Path;

use mlx::Dtype;

use ironmlx::core::generate::{GenerateRequest, GenerationStream, IMAGE_TOKEN_ID};
use ironmlx::core::{Loader, Sampler, Tokenizer};
use ironmlx::models::Qwen35Model;

const FIXTURE_DIR: &str = "tests/fixtures/p6_qwen35_vl/multi_image";

fn load_npy_int32(path: &str) -> mlx::Array {
    mlx::io::load_npy(path).unwrap_or_else(|e| panic!("load {path}: {e}"))
}

/// Load pixel_values from the safetensors fixture.
///
/// The fixture stores `[N_total, 1536]` (C-major, mlx-vlm layout).
/// We reshape to `[N, 3, 2, 16, 16]` (N, C, T, H, W) and then
/// transpose to `[N, 2, 3, 16, 16]` (N, T, C, H, W) as required by
/// ironmlx PatchEmbed. Finally cast to bf16.
fn load_pv_safetensors(path: &str) -> mlx::Array {
    let (mut t, _) = mlx::io::load_safetensors(path).unwrap_or_else(|e| panic!("load {path}: {e}"));
    let flat = t.remove("tensor").expect("tensor key");
    let n_total = flat.shape().as_slice()[0];
    let pv_5d = flat
        .reshape(&[n_total, 3, 2, 16, 16][..])
        .expect("reshape pv to [N, C, T, H, W]");
    let pv = mlx::ops::shape::transpose_axes(&pv_5d, &[0_i32, 2, 1, 3, 4][..])
        .expect("transpose pv to [N, T, C, H, W]");
    mlx::ops::cast::astype(&pv, Dtype::Bfloat16).expect("cast pv bf16")
}

#[test]
#[ignore = "requires QWEN35_MODEL env + P6.6 fixture in multi_image/"]
fn p6_7_chunked_prefill_matrix() {
    let model_dir = std::env::var("QWEN35_MODEL").expect("QWEN35_MODEL");
    let loader = Loader::open_multimodal(Path::new(&model_dir)).expect("loader");
    let tokenizer = Tokenizer::from_loader(&loader).expect("tokenizer");
    let model = Qwen35Model::from_loader(&loader).expect("model");

    // Load fixture (N=2 or N=3, depending on what run_p6_6_diff.sh produced last).
    let input_ids_arr = load_npy_int32(&format!("{FIXTURE_DIR}/expected_input_ids.npy"));
    let input_ids_i32: Vec<i32> = mlx::ops::cast::astype(&input_ids_arr, Dtype::Int32)
        .expect("cast input_ids")
        .to_vec::<i32>()
        .expect("input_ids vec");
    let prompt_ids: Vec<u32> = input_ids_i32.iter().map(|&i| i as u32).collect();

    let grid_arr = load_npy_int32(&format!("{FIXTURE_DIR}/expected_image_grid_thw.npy"));
    let grids_flat: Vec<i32> = mlx::ops::cast::astype(&grid_arr, Dtype::Int32)
        .expect("cast grid")
        .to_vec::<i32>()
        .expect("grid vec");
    let grids: Vec<(i32, i32, i32)> = grids_flat
        .chunks_exact(3)
        .map(|c| (c[0], c[1], c[2]))
        .collect();
    let n_images = grids.len();
    eprintln!(
        "[p6_7] N images = {}, prompt_len = {}",
        n_images,
        prompt_ids.len()
    );

    let expected_token: i32 =
        std::fs::read_to_string(format!("{FIXTURE_DIR}/expected_first_token.txt"))
            .expect("read first_token")
            .trim()
            .parse()
            .expect("parse first_token");
    eprintln!("[p6_7] expected first token = {}", expected_token);

    let stop_token_ids = tokenizer.eos_token_ids().to_vec();

    // Drive 3 chunk_size points. Reload pv per point since GenerateRequest
    // takes ownership.
    let chunk_sizes = [0_usize, 256, 64];
    for &cs in &chunk_sizes {
        let pv = load_pv_safetensors(&format!("{FIXTURE_DIR}/expected_pixel_values.safetensors"));
        let request = GenerateRequest {
            prompt_ids: prompt_ids.clone(),
            max_new_tokens: 1,
            sampler: Sampler::greedy(),
            stop_token_ids: stop_token_ids.clone(),
            prefill_chunk_size: cs,
            decode_cadence_mid_chunk_cap: 256,
            pixel_values: Some(vec![pv]),
            image_grid_thw: Some(grids.clone()),
            image_spatial_merge_size: 2,
            image_token_id: IMAGE_TOKEN_ID,
            #[cfg(feature = "p5h-profile")]
            p5h_trace: None,
            #[cfg(feature = "p5h-profile")]
            p5h_root_span: None,
        };

        let mut stream = GenerationStream::new(&model, &tokenizer, request).expect("stream::new");
        let event = stream
            .next_token()
            .expect("next_token error")
            .expect("next_token returned None unexpectedly");
        let got = event.token as i32;
        eprintln!("[p6_7] chunk_size={:>4}: first_token = {}", cs, got);
        assert_eq!(
            got,
            expected_token,
            "P6.7 chunked prefill first-token mismatch at chunk_size={cs}: got {got}, expected {expected_token}"
        );
    }
    eprintln!(
        "[p6_7] PASS — all chunk_sizes match expected_token={}",
        expected_token
    );
}
