//! Task 14 — P6 VL: `build_position_ids_vl` fixture comparison.
//!
//! Reference fixture generated by `LanguageModel.get_rope_index` from
//! mlx-vlm (`qwen3_vl/language.py:333-486`) with:
//!   input_ids = [100, 101, 248053, 248056×260, 248054, 102, 103]
//!   grid_thw  = [[1, 26, 40]]  → llm_grid (1, 13, 20), 260 image tokens
//!
//! The fixture stores int32 arrays; comparison is exact (integer equality).

use ironmlx::core::generate::{build_position_ids_vl, IMAGE_TOKEN_ID};

const FIXTURE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/p6_qwen35_vl/p6_pos_ids_ref.safetensors"
);

#[test]
fn build_position_ids_vl_matches_mlx_vlm() {
    let (tensors, _meta) =
        mlx::io::load_safetensors(FIXTURE).expect("failed to load p6_pos_ids_ref.safetensors");

    let input_ids_arr = tensors.get("input_ids").expect("missing input_ids");
    let grid_arr = tensors.get("grid_thw").expect("missing grid_thw");
    let expected = tensors.get("pos_ids").expect("missing pos_ids");

    // input_ids: shape [1, 266] — flatten to Vec<i32>
    let ids_flat: Vec<i32> = input_ids_arr.to_vec().expect("input_ids to_vec");
    // grid_thw: shape [1, 3] — one (t,h,w) tuple
    let grids_flat: Vec<i32> = grid_arr.to_vec().expect("grid_thw to_vec");
    let grid_tuples: Vec<(i32, i32, i32)> = grids_flat
        .chunks_exact(3)
        .map(|c| (c[0], c[1], c[2]))
        .collect();

    let spatial_merge_size = 2_i32;
    let our_pos =
        build_position_ids_vl(&ids_flat, &grid_tuples, IMAGE_TOKEN_ID, spatial_merge_size)
            .expect("build_position_ids_vl failed");

    // Shape must be [3, 1, S]
    let exp_shape = expected.shape();
    let our_shape = our_pos.shape();
    assert_eq!(
        our_shape.as_slice(),
        exp_shape.as_slice(),
        "shape mismatch: ours={our_shape:?} expected={exp_shape:?}"
    );

    let our_vec: Vec<i32> = our_pos.to_vec().expect("our_pos to_vec");
    let exp_vec: Vec<i32> = expected.to_vec().expect("expected to_vec");

    assert_eq!(
        our_vec.len(),
        exp_vec.len(),
        "element count mismatch: {} vs {}",
        our_vec.len(),
        exp_vec.len()
    );

    // Integer exact — no tolerance.
    let mut mismatch_count = 0usize;
    for (i, (o, e)) in our_vec.iter().zip(&exp_vec).enumerate() {
        if o != e {
            if mismatch_count < 10 {
                eprintln!("  mismatch at flat index {i}: ours={o} expected={e}");
            }
            mismatch_count += 1;
        }
    }
    assert_eq!(
        mismatch_count,
        0,
        "{mismatch_count} element(s) differ out of {} total",
        our_vec.len()
    );

    eprintln!(
        "build_position_ids_vl PASS — {} elements compared, all exact",
        our_vec.len()
    );
}
